### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [rawstudio/rawstudio#36]
Could you add versioned tarballs here on GitHub? Thank you.

**Comment by abrander** [comment]
That's a nice idea!

**Comment by abrander** [comment]
This comment is for holding release assets.

![aaa](https://cloud.githubusercontent.com/assets/3726205/25037639/8e88a620-20fa-11e7-8d99-b9b015b220f6.jpg)

**Comment by abrander** [comment]
All releases properly tagged and described here.

That was an interesting trip down memory lane. Who knew that it's almost 11 years since we made the first formal release of Rawstudio?! :)

https://github.com/rawstudio/rawstudio/releases/

**Comment by baimafeima** [comment]
@abrander Thanks, a lot and great to see the release history. I didn't know the last release was from 2011, then I guess my request to include Rawstudio in the Solus repositories won't be successful: https://dev.solus-project.com/T3043
How far away are you from releasing the next version?

**Comment by sergiomb2** [comment]
Since last release 2.0 (2011) we got several components updates like gtk2 to gtk3 and rawspeed version but not development on rawstudio functionality, so I advise you to use last git head master version (may be one day it will be 2.1 [1] ) . 
I pack it in Fedora [2] , after components update it haven't almost any change, just bug fixing and drop things that stop to work or compile correctly like osm-gps-map [3] . 

[1] AC_INIT([rawstudio], [2.1])

[2] https://apps.fedoraproject.org/packages/rawstudio 

[3] https://apps.fedoraproject.org/packages/osm-gps-map 
https://github.com/nzjrs/osm-gps-map/releases

**Comment by baimafeima** [comment]
> Since last release 2.0 (2011) we got several components updates like gtk2 to gtk3

It would be great to release a new version then. Master.zip won't help to get it included.

**Comment by alerque** [comment]
Agree. Things like GTK2→GTK3 definitely need to be rolled as releases. As a packager for a couple of distros we can't keep fresh software in front of people in upstream's don't tag releases and if things like dependencies change that has to be a release so we can adjust the build process at the right points.

**Comment by baimafeima** [comment]
What do you think? @abrander

**Comment by sergiomb2** [comment]
I vote on tag, git master branch (https://github.com/rawstudio/rawstudio/commit/ea57ba19d0b8d0427b7be49ba2570b3fccf3a06f) with 2.1.beta1 or 2.0.90  , the code was on Fedora package since Feb 2016

**Comment by jerekupari** [comment]
> Since last release 2.0 (2011) we got several components updates like gtk2 to gtk3 and rawspeed version but not development on rawstudio functionality

Actually after that 2011 official 2.0 there's been tons of new features. Advanced color profiles, the later dropped geo-tagging, enfuse, at least. But there might have been some 2.0 named versions in some distros, that were actually based on later developments.

I think the new gtk3 version does not have any new functionality compared to latest gtk2 master, and the gtk3-version is still not ready for release. The 2.1 Milestones plus #25 and #27 are the worst issues in my view.

If I could wish anything, the latest gtk2 version would be released as 2.1, as soon as possible. And the gtk3 version would be 2.2 or 3.0 when it is ready. Maybe it's funny to have a 3.0 that has no new features compared to 2.1, but everyone else seems to raise their version numbers very fast these days.

But, it could be that the gtk2 version has hi-dpi issues, and there were some security issues at some point. Are they fixed in that, or are they easy to pick from later commits?

**Comment by jerekupari** [comment]
By the way, there is a 2.1 feature freeze from the end of 2011 :)
https://rawstudio.org/blog/?p=788

**Comment by sergiomb2** [comment]
2.1 it wasn't released yet , but if you prefer we may call it 2.2-(pre1)(beta1)(rc0) with changelog last more or less 230 commits , about migration gtk2 gtk3 etc just to keep it alive. I don't know if 2.1 features are completed.

**Comment by sergiomb2** [comment]
589 commits , I definitely agree that we should have one tag

**Comment by jerekupari** [comment]
> I don't know if 2.1 features are completed.

If you mean the 2011 feature freeze I linked, those features were complete at some point and worked for me perfectly. Since then at least the Advanced color profiles have disappeared (#27). 

The last fully working version (for me at least) was 30e4efb, but it probably won't compile on modern distros unless the geo support (trivial, even I could do it!) and dcraw are removed.

**Comment by abrander** [comment]
I'll try to address all comments.

Rawstudio is not seing much development these days. Rawstudio is a big project. When we we're preparing v2.1 we we're 4 core developers people working on the project. Nowadays it's me and pull requests. People got other priorities, kids, houses and spouses. A lot happens in ten years.

If there shall ever be a new release of Rawstudio (which I think there should!) at least one of these must happen:

1) The code base must be simpler. All functionality not directly related to developing raw images must be removed.

2) Someone with a lot of time should take over maintainership.

**Comment by sergiomb2** [comment]
I don't understand why this 2 point must happen, we don't want a release we want one tag , for organization of downstream i.e. distro packagers.

**Comment by baimafeima** [comment]
> The code base must be simpler. All functionality not directly related to developing raw images must be removed.

I agree with this. Narrowing it down to its core functionality will ensure that an application like Rawstudio survives among the many fully-featured image applications. It will also make maintenance much easier. Nevertheless, I think a new tagged release is necessary. Getting Rawstudio included in various distributions exposes it to a much wider user base and this in turn will ensure people report bugs and care about its continued development.

**Comment by sergiomb2** [comment]
> I think a new tagged release is necessary. Getting Rawstudio included in various distributions exposes it to a much wider user base and this in turn will ensure people report bugs and care about its continued development.

100% agree , @abrander you may tag a pre-release please ? , otherwise our work was useless .
